### ISSUE TITLE
Duda con CheckMac

### ISSUE THREAD

**Issue by ghost** [NinjasCL-archive/prestashop-webpay#24]
Hola!

No se si puedo hacer la pregunta ya que es más de negocio pero...transbank me solicita una porción de código donde realiza la validacion de la checkmac en la pagina de cierre. Me podrias ayudar con ese tema ya que sinceramente no se que está pidiendo esa empresa jajaja. Saludos!

**Comment by clsource** [comment]
ese es el archivo validate.php
adjuntalo en el documento de certificacion :+1: 

saludos
